[package]
name = "kittynode_core"
description.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
eyre = "0.6.12"

[dev-dependencies]
tempfile = "3"
