[package]
name = "kittynode_core"
description.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
bollard = "0.17.1"
eyre = "0.6.12"
tracing = "0.1.40"

[dev-dependencies]
tempfile = "3"
